name: CI

on:
  # Make this workflow manual-only to avoid running on every push/PR
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest
      - name: Ruff (lint)
        run: |
          source venv/bin/activate
          ruff check .
      - name: Pytest
        env:
          PYTEST_ADDOPTS: "-q"
        run: |
          source venv/bin/activate
          pytest

